arm: mach-msm: remove duplicated battery
bms-batterydata-oem.c definitions are already included in bms-batterydata-flamingo.c so the first one should not be compiled.
This fixes the error:
arch/arm/mach-msm/bms-batterydata-flamingo.o:(.data.rel.local+0x0): multiple definition of `oem_batt_data'
arch/arm/mach-msm/bms-batterydata-oem.o:(.data.rel.local+0x0): first defined here